/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author domit
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    List<String> filesTypes = new ArrayList<>(Arrays.asList("log", "txt"));
    List<File> listFiles = new ArrayList<>();

    public Frame() {
        initComponents();
        textError.setVisible(false);
        enableDragAndDrop();
    }

    private void enableDragAndDrop() {
        DropTarget target = new DropTarget(dropTextArea, new DropTargetListener() {
            public void dragEnter(DropTargetDragEvent e) {
            }

            public void dragExit(DropTargetEvent e) {
            }

            public void dragOver(DropTargetDragEvent e) {
            }

            public void dropActionChanged(DropTargetDragEvent e) {
            }

            public void drop(DropTargetDropEvent e) {
                try {
                    e.acceptDrop(DnDConstants.ACTION_COPY_OR_MOVE);
                    List list = (java.util.List) e.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    list.forEach(v -> {
                        File file = (File) v;
                        if (filesTypes.contains(file.getName().split("\\.")[1])) {
                            dropTextArea.append(file.getName() + "\n");
                            listFiles.add(file);
                        }
                    });
                    if(listFiles.size() > 0){
                        InfoLabel.setVisible(false);
                    }
                } catch (Exception ex) {
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();
        buttonChooseFiles = new javax.swing.JButton();
        textError = new javax.swing.JLabel();
        InfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dropTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 375));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Introduce los fichero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonNext.setText("Avanzar");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        buttonChooseFiles.setText("Elegir ficheros");
        buttonChooseFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseFilesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonChooseFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, -1, -1));

        textError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textError.setForeground(new java.awt.Color(255, 0, 0));
        textError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textError.setText("Por favor introduca algún fichero.");
        getContentPane().add(textError, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, 306, -1));

        InfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoLabel.setText("Arrastre un fichero aqui :D");
        getContentPane().add(InfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        dropTextArea.setEditable(false);
        dropTextArea.setColumns(20);
        dropTextArea.setRows(5);
        jScrollPane1.setViewportView(dropTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 388, 219));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChooseFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseFilesActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("All files", "log", "txt"));
        fileChooser.setMultiSelectionEnabled(true);
        int returnVal = fileChooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] files = fileChooser.getSelectedFiles();
            for (File file : files) {
                dropTextArea.append(file.getName() + "\n");
                listFiles.add(file);
            }
        }
    }//GEN-LAST:event_buttonChooseFilesActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        if (dropTextArea.getText().length() > 0) {
            List<String> fileNames = new ArrayList<>();
            for (File listFile : listFiles) {
                fileNames.add(listFile.getName());
            }
            FrameDifferentiator frameDiff = new FrameDifferentiator(fileNames, listFiles);
            this.dispose();
            frameDiff.setVisible(true);
        }else{
            textError.setVisible(true);
        }
    }//GEN-LAST:event_buttonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JButton buttonChooseFiles;
    private javax.swing.JButton buttonNext;
    private javax.swing.JTextArea dropTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textError;
    // End of variables declaration//GEN-END:variables
}
