/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerInt;
import Model.Atomo.FileData;
import Model.Atomo.Molecule;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author daviddiaz
 */
public class FrameDifferentiator extends javax.swing.JFrame {

    /**
     * Creates new form FrameDifferentiator to show the tables.
     */
    private List<String> files = new ArrayList<>();
    private List<File> filesData = new ArrayList<>();
    private JPanel panelGeneric = new JPanel();
    private List<String> names = new ArrayList<>();
    private List<File> usedFiles = new ArrayList<>();
    private List<JTable> usedTables = new ArrayList<>();
    private List<String> keywordsUsed = new ArrayList<>();
    private List<List<String>> rows = new ArrayList<>();
    List<String> colAndRows = new ArrayList<>();

    ControllerInt controller;
    JTable tableGeneric;

    public FrameDifferentiator(ControllerInt controller) {
        initComponents();
        this.controller = controller;
    }

    public FrameDifferentiator(List<String> files, List<File> filesData, ControllerInt controller) {
        initComponents();
        this.controller = controller;
        panelGeneric.setLayout(new GridLayout(0, 1));
        tabbedPane.addTab("Generic", panelGeneric);
        tabbedPane.setVisible(false);

        this.files = files;
        this.errorText.setVisible(true);
        this.filesData = filesData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCoordinates = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        fieldRow = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldColumn = new javax.swing.JTextField();
        buttonAddValue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaValues = new javax.swing.JTextArea();
        finishButton = new javax.swing.JButton();
        errorDialogCoor = new javax.swing.JLabel();
        dialogNombre = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        fieldNameValues = new javax.swing.JTextField();
        buttonValues = new javax.swing.JButton();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        comboOptions = new javax.swing.JComboBox<>();
        fieldKeyword = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        deleteButtton = new javax.swing.JButton();
        buttonExportCSV = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        buttonValue = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSearchValue = new javax.swing.JMenuItem();
        itemExport = new javax.swing.JMenuItem();
        itemReset = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();

        jLabel2.setText("Row:");

        jLabel3.setText("Column:");

        buttonAddValue.setText(">");
        buttonAddValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddValueActionPerformed(evt);
            }
        });

        areaValues.setEditable(false);
        areaValues.setColumns(3);
        areaValues.setRows(5);
        jScrollPane1.setViewportView(areaValues);

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        errorDialogCoor.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout dialogCoordinatesLayout = new javax.swing.GroupLayout(dialogCoordinates.getContentPane());
        dialogCoordinates.getContentPane().setLayout(dialogCoordinatesLayout);
        dialogCoordinatesLayout.setHorizontalGroup(
            dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                        .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCoordinatesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fieldRow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                        .addComponent(errorDialogCoor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton)))
                .addContainerGap())
        );
        dialogCoordinatesLayout.setVerticalGroup(
            dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                        .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(buttonAddValue))
                            .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                                .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(fieldRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(fieldColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCoordinatesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(dialogCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCoordinatesLayout.createSequentialGroup()
                        .addComponent(finishButton)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(errorDialogCoor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setText("Choose a name for the values");

        buttonValues.setText("Ok");
        buttonValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValuesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogNombreLayout = new javax.swing.GroupLayout(dialogNombre.getContentPane());
        dialogNombre.getContentPane().setLayout(dialogNombreLayout);
        dialogNombreLayout.setHorizontalGroup(
            dialogNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogNombreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonValues)
                    .addComponent(fieldNameValues, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dialogNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogNombreLayout.setVerticalGroup(
            dialogNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNameValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonValues)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search by keyword:");

        comboOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starts with", "Ends with", "Contains", "Range" }));

        fieldKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKeywordActionPerformed(evt);
            }
        });

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        deleteButtton.setText("Reset");
        deleteButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButttonActionPerformed(evt);
            }
        });

        buttonExportCSV.setText("Export to CSV");
        buttonExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportCSVActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 0, 0));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonValue.setText("Search value");
        buttonValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValueActionPerformed(evt);
            }
        });

        jMenu1.setText("Options");

        itemSearchValue.setText("Search values");
        itemSearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchValueActionPerformed(evt);
            }
        });
        jMenu1.add(itemSearchValue);

        itemExport.setText("Export to CSV");
        itemExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExportActionPerformed(evt);
            }
        });
        jMenu1.add(itemExport);

        itemReset.setText("Reset");
        itemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemResetActionPerformed(evt);
            }
        });
        jMenu1.add(itemReset);

        jMenuItem1.setText("Choose files");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(266, 266, 266))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAdd)
                        .addGap(77, 77, 77)
                        .addComponent(buttonValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExportCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButtton))
                    .addComponent(tabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd)
                    .addComponent(deleteButtton)
                    .addComponent(buttonValue)
                    .addComponent(buttonExportCSV))
                .addGap(15, 15, 15)
                .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method used to get the click event.
     *
     * @param evt
     */
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        actionButtonAdd();
    }//GEN-LAST:event_buttonAddActionPerformed

    /**
     * Creates a table with every single keyword.
     *
     * @return the table.
     */
    private JTable initTablesDifferentiators() {
        JTable table = new JTable();
        table.setAutoCreateRowSorter(true);
        List<String> singleNames = new ArrayList<>();
        singleNames.add("Gaussian");
        singleNames.add("Atom");

        names.stream().filter((file) -> (!singleNames.contains(file))).forEachOrdered((file) -> {
            singleNames.add(file);
        });
        boolean[] canEditTry = new boolean[singleNames.size()];
        for (int i = 0; i < canEditTry.length; i++) {
            canEditTry[i] = false;
        }
        DefaultTableModel model = new DefaultTableModel(
                singleNames.toArray(new String[0]),
                0) {
            boolean[] canEdit = canEditTry;

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Class<?> getColumnClass(int column) {
                Class<?> returnValue;
                if ((column >= 0) && (column < getColumnCount())) {
                    returnValue = getValueAt(0, column).getClass();
                } else {
                    returnValue = Object.class;
                }

                return returnValue;

            }
        ;
        };
        table.setModel(model);
        for (int i = 0; i < table.getColumnCount(); i++) {
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        return table;
    }

    /**
     * Method used to add rows to the table.
     *
     * @param table the table that we want to add rows to.
     * @return table with rows added.
     */
    private JTable addRowsToTable(JTable table) {
        JTable tableWithElements = table;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        List<FileData> fileData = this.controller.getFileData(usedFiles);
        String fileNameError = "";
        boolean correcto = false;
        for (String name : names) {
            salir:
            if (!correcto) {
                for (FileData fileData1 : fileData) {
                    if (fileData1.getFileName().equals(name)) {
                        fileNameError = "";
                        break salir;
                    } else {
                        correcto = true;
                        fileNameError = name;
                    }
                }
            }
        }
        if (fileData.size() == usedFiles.size()) {
            errorText.setText("");
            List<Object> data = new ArrayList<>();
            for (int i = 0; i < fileData.get(0).getAtoms().size(); i++) {
                data.clear();
                for (int j = 1; j < fileData.size() + 1; j++) {
                    if (j == 1) {
                        data.add(fileData.get(j - 1).getAtoms().get(i).getGaussianData());
                        data.add(fileData.get(j - 1).getAtoms().get(i).getAtom());
                    }
                    data.add(fileData.get(j - 1).getAtoms().get(i).getIsotropic());
                }
                model.addRow(data.toArray(new Object[0]));
            }
            return tableWithElements;
        } else {
            keywordsUsed.remove(fieldKeyword.getText());
            errorText.setText("Syntax error. Please, check the file " + fileNameError + ".");
            return table;
        }
    }

    /**
     * Add the used files to a List.F
     */
    private void getUsedFiles(String value) {
        //String.valueOf(comboOptions.getSelectedItem())
        switch (String.valueOf(comboOptions.getSelectedItem())) {
            case "Starts with":
                for (int i = 0; i < files.size(); i++) {
                    String filename = files.get(i).contains(".log") ? files.get(i).replace(".log", "") : files.get(i).replace(".txt", "");
                    if (filename.startsWith(value)) {
                        usedFiles.add(filesData.get(i));
                        if (!names.contains(filename)) {
                            names.add(filename);
                        }
                    }
                }
                break;
            case "Ends with":
                for (int i = 0; i < files.size(); i++) {
                    String filename = files.get(i).contains(".log") ? files.get(i).replace(".log", "") : files.get(i).replace(".txt", "");
                    if (filename.endsWith(value)) {
                        usedFiles.add(filesData.get(i));
                        names.add(filename);
                    }
                }
                break;
            case "Contains":
                for (int i = 0; i < files.size(); i++) {
                    String filename = files.get(i).contains(".log") ? files.get(i).replace(".log", "") : files.get(i).replace(".txt", "");
                    if (filename.contains(value)) {
                        usedFiles.add(filesData.get(i));
                        names.add(filename);
                    }
                }
                break;
            default:
                break;
        }
    }

    /**
     * The same function that button add.
     *
     * @param evt
     */
    private void fieldKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKeywordActionPerformed
        actionButtonAdd();
    }//GEN-LAST:event_fieldKeywordActionPerformed

    /**
     * Gets column and rows.
     *
     * @param evt
     */
    private void buttonAddValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddValueActionPerformed
        String regex = "\\d+";
        if (fieldRow.getText().matches(regex) && fieldColumn.getText().matches(regex)) {
            int row = Integer.parseInt(fieldRow.getText());
            int column = Integer.parseInt(fieldColumn.getText());
            if (row >= column) {
                colAndRows.add(row + "," + column);
                areaValues.append(row + "," + column + "\n");
                errorDialogCoor.setText("");
            } else {
                errorDialogCoor.setText("<html><body>The value of the row must be greater<br>than or equal to the column value.</body></html>");
            }
        } else {
            errorDialogCoor.setText("The values need to be integer.");
        }
        fieldRow.setText("");
        fieldColumn.setText("");

    }//GEN-LAST:event_buttonAddValueActionPerformed

    /**
     * Closes the dialog and opens the dialog that asks for a name.
     *
     * @param evt
     */
    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        errorDialogCoor.setText("");
        areaValues.setText("");
        dialogCoordinates.dispose();
        dialogNombre.pack();
        dialogNombre.setVisible(true);
    }//GEN-LAST:event_finishButtonActionPerformed

    /**
     * Gets the name of the table and creates it with all the data from the
     * coordinates.
     *
     * @param evt
     */
    private void buttonValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValuesActionPerformed
        JPanel newPane = new JPanel();
        newPane.setLayout(new GridLayout(0, 1));
        String[] values = new String[keywordsUsed.size() + 2];
        values[0] = "Row";
        values[1] = "Column";
        for (int i = 2; i < keywordsUsed.size() + 2; i++) {
            values[i] = keywordsUsed.get(i - 2);
        }

        JTable tableCoord = new JTable();
        boolean[] canEditTry = new boolean[2 + keywordsUsed.size()];
        for (int i = 0; i < canEditTry.length; i++) {
            canEditTry[i] = false;
        }

        DefaultTableModel modelTable = new DefaultTableModel(values, 0) {
            boolean[] canEdit = canEditTry;

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Class<?> getColumnClass(int column) {
                Class<?> returnValue;
                if ((column >= 0) && (column < getColumnCount())) {
                    returnValue = getValueAt(0, column).getClass();
                } else {
                    returnValue = Object.class;
                }

                return returnValue;

            }
        ;
        };
        tableCoord.setModel(modelTable);
        //Center columns
        for (int i = 0; i < tableCoord.getColumnCount(); i++) {
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            tableCoord.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tableCoord.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        tableCoord.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));

        DefaultTableModel model = (DefaultTableModel) tableCoord.getModel();

        List<Molecule> molList = new ArrayList<>();

        for (int i = 2; i < tableCoord.getColumnCount(); i++) {
            usedFiles.clear();
            getUsedFiles(tableCoord.getColumnName(i));
            Molecule mole = controller.getTableMolecule(usedFiles, colAndRows, tableCoord.getColumnName(i));
            molList.add(mole);
        }

        List<List<String>> rows = new ArrayList<>();
        for (int i = 0; i < colAndRows.size(); i++) {
            List<String> val = new ArrayList<>();
            String[] coord = colAndRows.get(i).split(",");
            val.add(coord[0]);
            val.add(coord[1]);
            for (int j = 0; j < molList.size(); j++) {
                val.add(String.valueOf(molList.get(j).getResult().get(i).getValue()));
            }
            rows.add(val);
        }

        rows.forEach((row) -> {
            model.addRow(row.toArray());
        });

        usedTables.add(tableCoord);
        JScrollPane scrollpaneHola = new JScrollPane(tableCoord, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        newPane.add(scrollpaneHola);
        tabbedPane.insertTab(fieldNameValues.getText(), new ImageIcon(""), newPane, null, 1);
        dialogNombre.dispose();
        fieldNameValues.setText("");
    }//GEN-LAST:event_buttonValuesActionPerformed

    private void itemSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchValueActionPerformed
        dialogCoordinates.pack();
        dialogCoordinates.setVisible(true);
        colAndRows.clear();
    }//GEN-LAST:event_itemSearchValueActionPerformed

    private void itemExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExportActionPerformed
        errorText.setForeground(Color.red);
        String folder = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.exists()) {
                new File(file.getAbsolutePath()).mkdir();
            }
            folder = file.getAbsolutePath();
        }

        keywordsUsed.add("Generic");

        if (usedTables.size() > 0) {
            for (int i = 0; i < keywordsUsed.size(); i++) {
                List<String[]> datas = new ArrayList<>();
                TableModel model = usedTables.get(i).getModel();
                String[] columnNames = new String[model.getColumnCount()];
                for (int j = 0; j < model.getColumnCount(); j++) {
                    columnNames[j] = model.getColumnName(j);
                }
                datas.add(columnNames);
                for (int k = 0; k < model.getRowCount(); k++) {
                    String[] data = new String[model.getColumnCount()];
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        if (model.getValueAt(k, j) != null && model.getValueAt(k, j).toString().trim().length() != 0) {
                            data[j] = String.valueOf(model.getValueAt(k, j));
                        }
                    }
                    datas.add(data);
                }
                if (this.controller.writeCSV(datas, folder, keywordsUsed.get(i))) {
                    errorText.setForeground(Color.green);
                    errorText.setText("All files has been created.");
                }
            }
        }
    }//GEN-LAST:event_itemExportActionPerformed

    private void itemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResetActionPerformed
        errorText.setText("");
        errorText.setForeground(Color.red);
        keywordsUsed.clear();
        tabbedPane.removeAll();
        tabbedPane.addTab("Generic", panelGeneric);
        tabbedPane.setVisible(false);
        panelGeneric.removeAll();
        tableGeneric = null;
    }//GEN-LAST:event_itemResetActionPerformed

    /**
     * Clears all the tables.
     *
     * @param evt
     */
    private void deleteButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButttonActionPerformed
        errorText.setText("");
        errorText.setForeground(Color.red);
        keywordsUsed.clear();
        tabbedPane.removeAll();
        tabbedPane.addTab("Generic", panelGeneric);
        tabbedPane.setVisible(false);
        panelGeneric.removeAll();
        tableGeneric = null;
    }//GEN-LAST:event_deleteButttonActionPerformed

    /**
     * Method used to export the tables to a CSV file
     *
     * @param evt
     */
    private void buttonExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportCSVActionPerformed
        errorText.setForeground(Color.red);
        String folder = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.exists()) {
                new File(file.getAbsolutePath()).mkdir();
            }
            folder = file.getAbsolutePath();
        }

        keywordsUsed.add("Generic");

        if (usedTables.size() > 0) {
            for (int i = 0; i < keywordsUsed.size(); i++) {
                List<String[]> datas = new ArrayList<>();
                TableModel model = usedTables.get(i).getModel();
                String[] columnNames = new String[model.getColumnCount()];
                for (int j = 0; j < model.getColumnCount(); j++) {
                    columnNames[j] = model.getColumnName(j);
                }
                datas.add(columnNames);
                for (int k = 0; k < model.getRowCount(); k++) {
                    String[] data = new String[model.getColumnCount()];
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        if (model.getValueAt(k, j) != null && model.getValueAt(k, j).toString().trim().length() != 0) {
                            data[j] = String.valueOf(model.getValueAt(k, j));
                        }
                    }
                    datas.add(data);
                }
                if (this.controller.writeCSV(datas, folder, keywordsUsed.get(i))) {
                    errorText.setForeground(Color.green);
                    errorText.setText("All files has been created.");
                }
            }
        }
    }//GEN-LAST:event_buttonExportCSVActionPerformed

    /**
     * Shows the dialog that gets the column and rows.
     *
     * @param evt
     */
    private void buttonValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValueActionPerformed
        dialogCoordinates.pack();
        dialogCoordinates.setVisible(true);
        colAndRows.clear();
    }//GEN-LAST:event_buttonValueActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ChooseFilesFrame chooseFilesFrame = new ChooseFilesFrame(controller);
        chooseFilesFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    /**
     * Creates the "generic" table with all the info from the other tables.
     *
     * @param usedFiles
     */
    private void genericTable(List<File> usedFiles) {
        Molecule molecule = this.controller.getMolecule(usedFiles, fieldKeyword.getText());
        String[] values = new String[keywordsUsed.size() + 2];
        values[0] = "Gaussian";
        values[1] = "Atom";
        for (int i = 2; i <= keywordsUsed.size() + 1; i++) {
            values[i] = keywordsUsed.get(i - 2);
        }

        if (tableGeneric == null) {
            initGenericTable(values);
            addElementsToGeneric(molecule);
            JScrollPane scrollpaneGeneric = new JScrollPane(tableGeneric, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            panelGeneric.add(scrollpaneGeneric);
        } else {
            panelGeneric.removeAll();
            initGenericTable(values);
            addElementsToGeneric(molecule);
            JScrollPane scrollpaneGeneric = new JScrollPane(tableGeneric, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            panelGeneric.add(scrollpaneGeneric);

        }
        TableColumn column = null;
        for (int i = 0; i < tableGeneric.getColumnCount(); i++) {
            if (i == 0 || i == 1) {
                column = tableGeneric.getColumnModel().getColumn(i);
                column.setMinWidth(100);
            } else {
                column = tableGeneric.getColumnModel().getColumn(i);
                column.setMinWidth(200);
            }
        }
        tableGeneric.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    /**
     * Initializes the generic table.
     *
     * @param values are the "keywords" used.
     */
    private void initGenericTable(String[] values) {
        tableGeneric = new JTable();

        boolean[] canEditTry = new boolean[keywordsUsed.size() + 2];
        for (int i = 0; i < canEditTry.length; i++) {
            canEditTry[i] = false;
        }

        DefaultTableModel modelGeneric = new DefaultTableModel(values, 0) {
            boolean[] canEdit = canEditTry;

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Class<?> getColumnClass(int column) {
                Class<?> returnValue;
                if ((column >= 0) && (column < getColumnCount())) {
                    returnValue = getValueAt(0, column).getClass();
                } else {
                    returnValue = Object.class;
                }

                return returnValue;

            }
        ;
        };
        tableGeneric.setAutoCreateRowSorter(true);
        tableGeneric.setModel(modelGeneric);
        //Center columns
        for (int i = 0; i < tableGeneric.getColumnCount(); i++) {
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            tableGeneric.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tableGeneric.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        tableGeneric.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
    }

    /**
     * Add all the elements to the generic table.
     *
     * @param molecule contains all the necessary info about the molecules.
     */
    private void addElementsToGeneric(Molecule molecule) {

        DefaultTableModel model = (DefaultTableModel) tableGeneric.getModel();
        List<List<String>> auxList = new ArrayList<>(rows);
        rows.clear();

        for (int i = 0; i < molecule.getResult().size(); i++) {
            if (keywordsUsed.size() == 1) {
                List<String> values = new ArrayList<>();
                values.add(molecule.getResult().get(i).getGaussian());
                values.add(molecule.getResult().get(i).getAtom());
                values.add(molecule.getResult().get(i).getValue().toString());
                rows.add(values);
            } else {
                List<String> values = new ArrayList<>(auxList.get(i));
                values.add(molecule.getResult().get(i).getValue().toString());
                rows.add(values);
            }
        }

        rows.forEach((row) -> {
            model.addRow(row.toArray());
        });

    }

    /**
     * This methos is used by buttonAdd and textField.s
     */
    private void actionButtonAdd() {
        errorText.setForeground(Color.red);
        if (fieldKeyword.getText().length() > 0) {
            if (!keywordsUsed.contains(fieldKeyword.getText())) {
                keywordsUsed.add(fieldKeyword.getText());
            }
            names.clear();
            usedFiles.clear();
            getUsedFiles(fieldKeyword.getText());
            if (!usedFiles.isEmpty()) {
                errorText.setText("");
                JTable table = addRowsToTable(initTablesDifferentiators());
                if (table.getRowCount() != 0) {
                    JPanel panel = new JPanel();
                    tabbedPane.setVisible(true);
                    panel.setLayout(new GridLayout(0, 1));
                    JScrollPane scrollpane = new JScrollPane(table, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                    TableColumn column = null;
                    for (int i = 0; i < table.getColumnCount(); i++) {
                        if (i == 0 || i == 1) {
                            column = table.getColumnModel().getColumn(i);
                            column.setMinWidth(100);
                        } else {
                            column = table.getColumnModel().getColumn(i);
                            column.setMinWidth(300);
                        }
                    }
                    table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                    panel.add(scrollpane);
                    tabbedPane.addTab(fieldKeyword.getText(), panel);
                    tabbedPane.setSelectedIndex(tabbedPane.getTabCount() - 1);
                    genericTable(usedFiles);
                    if (usedTables.isEmpty()) {
                        usedTables.add(tableGeneric);
                    }
                    usedTables.add(table);
                    revalidate();
                    pack();
                } else {
                    errorText.setText("Couldn't find any file with the provided keyword.");
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaValues;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAddValue;
    private javax.swing.JButton buttonExportCSV;
    private javax.swing.JButton buttonValue;
    private javax.swing.JButton buttonValues;
    private javax.swing.JComboBox<String> comboOptions;
    private javax.swing.JButton deleteButtton;
    private javax.swing.JDialog dialogCoordinates;
    private javax.swing.JDialog dialogNombre;
    private javax.swing.JLabel errorDialogCoor;
    private javax.swing.JLabel errorText;
    private javax.swing.JTextField fieldColumn;
    private javax.swing.JTextField fieldKeyword;
    private javax.swing.JTextField fieldNameValues;
    private javax.swing.JTextField fieldRow;
    private javax.swing.JButton finishButton;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemExport;
    private javax.swing.JMenuItem itemReset;
    private javax.swing.JMenuItem itemSearchValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
