/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.csv;

import Controller.csv.ControllerIntCsv;
import View.OptionsMenu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author domit
 */
public class MainFrame extends javax.swing.JFrame {

    FilterOptions fo = new FilterOptions(this);
    List<String[]> datas;
    protected ControllerIntCsv controller;
    protected InsertValuesTable insert = new InsertValuesTable(this);
    protected DecorateFrame decorate = new DecorateFrame(this);
    protected JPanel panelGeneric = new JPanel();
    protected String separator;
    JTable table;
    ExportCSV csv = new ExportCSV(this);
    File file;
    OrderElements oe = new OrderElements(this);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public MainFrame(ControllerIntCsv controller, File file, String separator) {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setPreferredSize(new Dimension(screenSize.width, screenSize.height));
        this.setMinimumSize(new Dimension(720, 480));
        this.pack();
        this.setLocationRelativeTo(null);
        this.panelGeneric.setLayout(new GridLayout(0, 1));
        this.file = file;
        this.controller = controller;
        this.separator = separator;
        decorate.addIcons();
        insert.insertValues(file.getAbsolutePath(), separator);
        fo.initCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogExport = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        buttonAceptarDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboColumn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textMinValue = new javax.swing.JTextField();
        textMaxValue = new javax.swing.JTextField();
        buttonFilter = new javax.swing.JButton();
        buttonDesc = new javax.swing.JButton();
        buttonAsc = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        errorText = new javax.swing.JLabel();
        exportButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        DialogExport.setTitle("DataPicker4J");

        jLabel4.setText("Write output filename:");

        textFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNameActionPerformed(evt);
            }
        });

        buttonAceptarDialog.setText("Accept");
        buttonAceptarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogExportLayout = new javax.swing.GroupLayout(DialogExport.getContentPane());
        DialogExport.getContentPane().setLayout(DialogExportLayout);
        DialogExportLayout.setHorizontalGroup(
            DialogExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogExportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DialogExportLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAceptarDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogExportLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DialogExportLayout.setVerticalGroup(
            DialogExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogExportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAceptarDialog)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DataPicker4J");

        jLabel1.setText("Column:");

        jLabel2.setText("Min value:");

        jLabel3.setText("Max Value:");

        textMinValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinValueActionPerformed(evt);
            }
        });

        textMaxValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaxValueActionPerformed(evt);
            }
        });

        buttonFilter.setText("Filter");
        buttonFilter.setMaximumSize(new java.awt.Dimension(102, 32));
        buttonFilter.setMinimumSize(new java.awt.Dimension(102, 32));
        buttonFilter.setPreferredSize(new java.awt.Dimension(102, 32));
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });

        buttonDesc.setText("Order desc.");
        buttonDesc.setMaximumSize(new java.awt.Dimension(130, 32));
        buttonDesc.setMinimumSize(new java.awt.Dimension(130, 32));
        buttonDesc.setPreferredSize(new java.awt.Dimension(130, 32));
        buttonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDescActionPerformed(evt);
            }
        });

        buttonAsc.setText("Order asc.");
        buttonAsc.setMaximumSize(new java.awt.Dimension(130, 32));
        buttonAsc.setMinimumSize(new java.awt.Dimension(130, 32));
        buttonAsc.setPreferredSize(new java.awt.Dimension(130, 32));
        buttonAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAscActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 51, 51));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        exportButton.setText("Export to CSV");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Options");

        jMenuItem3.setText("Choose file");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Main menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ComboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exportButton)))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(exportButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void buttonAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAscActionPerformed
        errorText.setText("");
        errorText.setForeground(Color.RED);
        try {
            if (table.getSelectedColumns().length == 2) {
                oe.orderElements(">");
            } else {
                errorText.setText("Please select 2 rows");
            }
        } catch (Exception e) {
            errorText.setText("This columns cannot be ordered");
        }
    }//GEN-LAST:event_buttonAscActionPerformed

    private void buttonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDescActionPerformed
        errorText.setText("");
        errorText.setForeground(Color.RED);
        try {
            if (table.getSelectedColumns().length == 2) {
                oe.orderElements("<");
            } else {
                errorText.setText("Please select 2 rows");
            }
        } catch (Exception e) {
            errorText.setText("This columns cannot be ordered");
        }
    }//GEN-LAST:event_buttonDescActionPerformed

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        fo.removeElements();
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void textMaxValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaxValueActionPerformed
        fo.removeElements();
    }//GEN-LAST:event_textMaxValueActionPerformed

    private void textMinValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMinValueActionPerformed
        fo.removeElements();
    }//GEN-LAST:event_textMinValueActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        OptionsMenu menu = new OptionsMenu();
        menu.setLocation(dim.width / 2 - menu.getSize().width / 2, dim.height / 2 - menu.getSize().height / 2);
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        ChooseCsvFile csf = new ChooseCsvFile(controller);
        csf.setLocation(dim.width / 2 - csf.getSize().width / 2, dim.height / 2 - csf.getSize().height / 2);
        csf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        DialogExport.setLocation(dim.width / 2 - DialogExport.getSize().width / 2, dim.height / 2 - DialogExport.getSize().height / 2);
        DialogExport.setVisible(true);
        DialogExport.pack();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void buttonAceptarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarDialogActionPerformed
        if (textFieldName.getText().length() > 0) {
            csv.exportToCSV(textFieldName.getText());
            textFieldName.setText("");
            DialogExport.dispose();
        }
    }//GEN-LAST:event_buttonAceptarDialogActionPerformed

    private void textFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNameActionPerformed
        if (textFieldName.getText().length() > 0) {
            csv.exportToCSV(textFieldName.getText());
            textFieldName.setText("");
            DialogExport.dispose();
        }
    }//GEN-LAST:event_textFieldNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboColumn;
    private javax.swing.JDialog DialogExport;
    private javax.swing.JButton buttonAceptarDialog;
    public javax.swing.JButton buttonAsc;
    public javax.swing.JButton buttonDesc;
    public javax.swing.JButton buttonFilter;
    public javax.swing.JLabel errorText;
    public javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField textFieldName;
    public javax.swing.JTextField textMaxValue;
    public javax.swing.JTextField textMinValue;
    // End of variables declaration//GEN-END:variables
}
